DROP TABLE IF EXISTS BUG;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON
(
  id        SERIAL PRIMARY KEY,
  LAST_NAME VARCHAR,
  NAME      VARCHAR
);

CREATE TABLE BUG
(
  id          SERIAL PRIMARY KEY,
  NAME        VARCHAR,
  RESOLUTION  VARCHAR,
  PRIORITY    VARCHAR,
  BUG_STATUS  VARCHAR,
  ASSIGNEE_ID INT REFERENCES PERSON (ID),
  REPORTER_ID INT REFERENCES PERSON (ID)
);
